sonar.projectKey=react-ts-realworld
sonar.sources=src
sonar.tests=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.gen.ts
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.typescript.tsconfigPaths=tsconfig.app.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.d.ts,src/**/*.gen.ts,src/test/**,src/main.tsx
