/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SettingsRouteImport } from './pages/settings'
import { Route as RegisterRouteImport } from './pages/register'
import { Route as LoginRouteImport } from './pages/login'
import { Route as FeedRouteImport } from './pages/feed'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ProfilesUsernameRouteImport } from './pages/profiles/$username'
import { Route as ArticlesCreateRouteImport } from './pages/articles/create'
import { Route as ArticlesSlugRouteImport } from './pages/articles/$slug'
import { Route as ProfilesUsernameFavoritesRouteImport } from './pages/profiles/$username_.favorites'
import { Route as ArticlesSlugEditRouteImport } from './pages/articles/$slug_.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesUsernameRoute = ProfilesUsernameRouteImport.update({
  id: '/profiles/$username',
  path: '/profiles/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesCreateRoute = ArticlesCreateRouteImport.update({
  id: '/articles/create',
  path: '/articles/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesUsernameFavoritesRoute =
  ProfilesUsernameFavoritesRouteImport.update({
    id: '/profiles/$username_/favorites',
    path: '/profiles/$username/favorites',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesSlugEditRoute = ArticlesSlugEditRouteImport.update({
  id: '/articles/$slug_/edit',
  path: '/articles/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/create': typeof ArticlesCreateRoute
  '/profiles/$username': typeof ProfilesUsernameRoute
  '/articles/$slug/edit': typeof ArticlesSlugEditRoute
  '/profiles/$username/favorites': typeof ProfilesUsernameFavoritesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/create': typeof ArticlesCreateRoute
  '/profiles/$username': typeof ProfilesUsernameRoute
  '/articles/$slug/edit': typeof ArticlesSlugEditRoute
  '/profiles/$username/favorites': typeof ProfilesUsernameFavoritesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/create': typeof ArticlesCreateRoute
  '/profiles/$username': typeof ProfilesUsernameRoute
  '/articles/$slug_/edit': typeof ArticlesSlugEditRoute
  '/profiles/$username_/favorites': typeof ProfilesUsernameFavoritesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/login'
    | '/register'
    | '/settings'
    | '/articles/$slug'
    | '/articles/create'
    | '/profiles/$username'
    | '/articles/$slug/edit'
    | '/profiles/$username/favorites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/login'
    | '/register'
    | '/settings'
    | '/articles/$slug'
    | '/articles/create'
    | '/profiles/$username'
    | '/articles/$slug/edit'
    | '/profiles/$username/favorites'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/login'
    | '/register'
    | '/settings'
    | '/articles/$slug'
    | '/articles/create'
    | '/profiles/$username'
    | '/articles/$slug_/edit'
    | '/profiles/$username_/favorites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesCreateRoute: typeof ArticlesCreateRoute
  ProfilesUsernameRoute: typeof ProfilesUsernameRoute
  ArticlesSlugEditRoute: typeof ArticlesSlugEditRoute
  ProfilesUsernameFavoritesRoute: typeof ProfilesUsernameFavoritesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$username': {
      id: '/profiles/$username'
      path: '/profiles/$username'
      fullPath: '/profiles/$username'
      preLoaderRoute: typeof ProfilesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/create': {
      id: '/articles/create'
      path: '/articles/create'
      fullPath: '/articles/create'
      preLoaderRoute: typeof ArticlesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$username_/favorites': {
      id: '/profiles/$username_/favorites'
      path: '/profiles/$username/favorites'
      fullPath: '/profiles/$username/favorites'
      preLoaderRoute: typeof ProfilesUsernameFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug_/edit': {
      id: '/articles/$slug_/edit'
      path: '/articles/$slug/edit'
      fullPath: '/articles/$slug/edit'
      preLoaderRoute: typeof ArticlesSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesCreateRoute: ArticlesCreateRoute,
  ProfilesUsernameRoute: ProfilesUsernameRoute,
  ArticlesSlugEditRoute: ArticlesSlugEditRoute,
  ProfilesUsernameFavoritesRoute: ProfilesUsernameFavoritesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
